name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        uses: nateraw/huggingface-sync-action@v0.0.4
        with:
          huggingface_repo_id: ILHAM78/Gemini-rag-app
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          private: false
